version: 2.9.pre.{build}
clone_folder: c:\pillow
init:
- ECHO %PYTHON%
environment:
  X64_EXT: -x64
  matrix:
  - PYTHON: C:/Python26
  - PYTHON: C:/Python32
  - PYTHON: C:/Python27-x64
  - PYTHON: C:/Python34
  - PYTHON: C:/Python27
  - PYTHON: C:/Python34-x64
install:
- IF [%PYTHON%]==[C:/Python26] appveyor DownloadFile https://www.python.org/ftp/python/2.6.6/python-2.6.6.msi
- IF [%PYTHON%]==[C:/Python26] msiexec /i python-2.6.6.msi /qn
- IF [%PYTHON%]==[C:/Python32] appveyor DownloadFile https://www.python.org/ftp/python/3.2.5/python-3.2.5.msi
- IF [%PYTHON%]==[C:/Python32] msiexec /i python-3.2.5.msi /qn
- pip install setuptools
- git clone https://github.com/wiredfool/pillow-depends.git c:\pillow-depends
- xcopy c:\pillow-depends\*.zip c:\pillow\winbuild\
- xcopy c:\pillow-depends\*.tar.gz c:\pillow\winbuild\
- cd c:\pillow\winbuild\
- c:\python34\python.exe c:\pillow\winbuild\build_dep.py
- c:\pillow\winbuild\build_deps.cmd
build_script:
- '%PYTHON%\python.exe c:\pillow\winbuild\build.py'
- cd c:\pillow
- '%PYTHON%\python.exe selftest.py --installed'
test_script:
- cd c:\pillow
- '%PYTHON%\Scripts\pip.exe install nose'
- '%PYTHON%\python.exe test-installed.py'
